server:
  port: 8081
  wait-time-in-ms-when-sync-empty: 3000

spring:
  spring:
    profiles:
      active: native
  data:
      mongodb:
        uri: mongodb://localhost:27017/Sales?authSource=admin&readPreference=primary&appname=MongoDB%20Compass&directConnection=true&ssl=false
        database: Sales
        auto-index-creation: true

application-version: 1.0