server:
  port: 8083
  wait-time-in-ms-when-sync-empty: 3000

spring:
  spring:
    profiles:
      active: native
  data:
      mongodb:
        uri: mongodb://localhost:27017/Sales?authSource=admin&readPreference=primary&appname=MongoDB%20Compass&directConnection=true&ssl=false
        database: Sales
        auto-index-creation: true

application:
  produtoService:
    url: http://localhost:8082
    endpointConsultarProduto: ${application.produtoService.url}/produto
  clienteService:
    url: http://localhost:8081
    endpointConsultarCliente: ${application.clienteService.url}/cliente/isCadastrado/{id}
application-version: 1.0